### ISSUE TITLE
Can't add widget

### ISSUE THREAD

**Issue by LaGGgggg** [SuperNova911/Gardener-for-GitHub#22]
Hey, I download app and can't add widget. App is good, but I really want to see it widgets. Write if you need more info about this bug.(I don't know what you need)

**Comment by SuperNova911** [comment]
Thanks for report @LaGGgggg 
Can you share more information? Device and OS Version would be good.

And I wonder if the Gardener widget itself is not visible in the widget gallery, or if the widget is added to home screen but does not show properly.

If widget does not show properly (like error message), Please share some screenshot.

**Comment by LaGGgggg** [comment]
iPhone XR, iOS 15.2.1. Yes, the widget itself is not displayed in the widget gallery.

**Comment by LaGGgggg** [comment]
I don't know what exactly was the problem, but reinstalling solved everything. Thank you for your attention to the bug, the app is very cool, thanks for the development:)
